/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  AuthResponse,
  LoginRequest,
  SignupRequest
} from '../api.schemas';

import { customInstance } from '.././axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary POST /auth/login - Login with existing account
 */
export const loginHandler = (
    loginRequest: LoginRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponse>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest, signal
    },
      options);
    }
  


export const getLoginHandlerMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginHandler>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof loginHandler>>, TError,{data: LoginRequest}, TContext> => {

const mutationKey = ['loginHandler'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginHandler>>, {data: LoginRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginHandler(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof loginHandler>>>
    export type LoginHandlerMutationBody = LoginRequest
    export type LoginHandlerMutationError = void

    /**
 * @summary POST /auth/login - Login with existing account
 */
export const useLoginHandler = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginHandler>>, TError,{data: LoginRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof loginHandler>>,
        TError,
        {data: LoginRequest},
        TContext
      > => {

      const mutationOptions = getLoginHandlerMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary POST /auth/logout - Logout and invalidate session
 */
export const logoutHandler = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<void>(
      {url: `/auth/logout`, method: 'POST', signal
    },
      options);
    }
  


export const getLogoutHandlerMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutHandler>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof logoutHandler>>, TError,void, TContext> => {

const mutationKey = ['logoutHandler'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutHandler>>, void> = () => {
          

          return  logoutHandler(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof logoutHandler>>>
    
    export type LogoutHandlerMutationError = void

    /**
 * @summary POST /auth/logout - Logout and invalidate session
 */
export const useLogoutHandler = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutHandler>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof logoutHandler>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLogoutHandlerMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary POST /auth/signup - Create a new user account
 */
export const signupHandler = (
    signupRequest: SignupRequest,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<AuthResponse>(
      {url: `/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signupRequest, signal
    },
      options);
    }
  


export const getSignupHandlerMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupHandler>>, TError,{data: SignupRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof signupHandler>>, TError,{data: SignupRequest}, TContext> => {

const mutationKey = ['signupHandler'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signupHandler>>, {data: SignupRequest}> = (props) => {
          const {data} = props ?? {};

          return  signupHandler(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignupHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof signupHandler>>>
    export type SignupHandlerMutationBody = SignupRequest
    export type SignupHandlerMutationError = void

    /**
 * @summary POST /auth/signup - Create a new user account
 */
export const useSignupHandler = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupHandler>>, TError,{data: SignupRequest}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof signupHandler>>,
        TError,
        {data: SignupRequest},
        TContext
      > => {

      const mutationOptions = getSignupHandlerMutationOptions(options);

      return useMutation(mutationOptions);
    }
    