/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
/**
 * The response payload sent after successfully creating a session.
 */
export interface CreateSessionResponse {
  document_id: string;
  session_id: string;
  user_id: string;
}

