/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
export interface AuthResponse {
  email: string;
  user_id: string;
}

/**
 * The response payload sent after successfully creating a session.
 */
export interface CreateSessionResponse {
  document_id: string;
  session_id: string;
  user_id: string;
}

export interface ListNotesResponse {
  notes: NoteItem[];
}

export interface ListSessionsResponse {
  sessions: SessionListItem[];
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface NoteItem {
  created_at: string;
  note_id: string;
  session_id: string;
  text: string;
}

export type SessionListItemTitle = string | null;

export interface SessionListItem {
  created_at: string;
  document_id: string;
  session_id: string;
  title?: SessionListItemTitle;
}

export interface SignupRequest {
  email: string;
  password: string;
}

