/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  CreateSessionResponse
} from '../api.schemas';

import { customInstance } from '../axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Requires authentication. The user_id is extracted from the auth session.
 * @summary Create a new session by uploading a document.
 */
export const createSessionHandler = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateSessionResponse>(
      {url: `/sessions`, method: 'POST', signal
    },
      options);
    }
  


export const getCreateSessionHandlerMutationOptions = <TError = void | void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSessionHandler>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createSessionHandler>>, TError,void, TContext> => {

const mutationKey = ['createSessionHandler'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSessionHandler>>, void> = () => {
          

          return  createSessionHandler(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateSessionHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof createSessionHandler>>>
    
    export type CreateSessionHandlerMutationError = void | void | void

    /**
 * @summary Create a new session by uploading a document.
 */
export const useCreateSessionHandler = <TError = void | void | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSessionHandler>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createSessionHandler>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCreateSessionHandlerMutationOptions(options);

      return useMutation(mutationOptions);
    }
    