/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * api
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSessionResponse,
  ListNotesResponse,
  ListSessionsResponse
} from '../api.schemas';

import { customInstance } from '../axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const listSessionsHandler = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListSessionsResponse>(
      {url: `/sessions`, method: 'GET', signal
    },
      options);
    }
  



export const getListSessionsHandlerQueryKey = () => {
    return [
    `/sessions`
    ] as const;
    }

    
export const getListSessionsHandlerQueryOptions = <TData = Awaited<ReturnType<typeof listSessionsHandler>>, TError = void>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listSessionsHandler>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSessionsHandlerQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSessionsHandler>>> = ({ signal }) => listSessionsHandler(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSessionsHandler>>, TError, TData> & { queryKey: QueryKey }
}

export type ListSessionsHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof listSessionsHandler>>>
export type ListSessionsHandlerQueryError = void



export function useListSessionsHandler<TData = Awaited<ReturnType<typeof listSessionsHandler>>, TError = void>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listSessionsHandler>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListSessionsHandlerQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Requires authentication. The user_id is extracted from the auth session.
 * @summary Create a new session by uploading a document.
 */
export const createSessionHandler = (
    
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<CreateSessionResponse>(
      {url: `/sessions`, method: 'POST', signal
    },
      options);
    }
  


export const getCreateSessionHandlerMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSessionHandler>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createSessionHandler>>, TError,void, TContext> => {

const mutationKey = ['createSessionHandler'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSessionHandler>>, void> = () => {
          

          return  createSessionHandler(requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateSessionHandlerMutationResult = NonNullable<Awaited<ReturnType<typeof createSessionHandler>>>
    
    export type CreateSessionHandlerMutationError = void

    /**
 * @summary Create a new session by uploading a document.
 */
export const useCreateSessionHandler = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSessionHandler>>, TError,void, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createSessionHandler>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getCreateSessionHandlerMutationOptions(options);

      return useMutation(mutationOptions);
    }
    export const listNotesHandler = (
    sessionId: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<ListNotesResponse>(
      {url: `/sessions/${sessionId}/notes`, method: 'GET', signal
    },
      options);
    }
  



export const getListNotesHandlerQueryKey = (sessionId?: string,) => {
    return [
    `/sessions/${sessionId}/notes`
    ] as const;
    }

    
export const getListNotesHandlerQueryOptions = <TData = Awaited<ReturnType<typeof listNotesHandler>>, TError = void>(sessionId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listNotesHandler>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListNotesHandlerQueryKey(sessionId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listNotesHandler>>> = ({ signal }) => listNotesHandler(sessionId, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(sessionId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listNotesHandler>>, TError, TData> & { queryKey: QueryKey }
}

export type ListNotesHandlerQueryResult = NonNullable<Awaited<ReturnType<typeof listNotesHandler>>>
export type ListNotesHandlerQueryError = void



export function useListNotesHandler<TData = Awaited<ReturnType<typeof listNotesHandler>>, TError = void>(
 sessionId: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listNotesHandler>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListNotesHandlerQueryOptions(sessionId,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




